apiVersion: hivepaas.com/v1
kind: TemplateTags
tags:
  - {id: sql, title: SQL}
  - {id: relational, title: Relational}
  - {id: open-source, title: Open Source}
  - {id: mysql-compatible, title: MySQL Compatible}
  - {id: document, title: Document}
  - {id: json, title: JSON}
  - {id: graph, title: Graph}
  - {id: time-series, title: Time Series}
  - {id: analytics, title: Analytics}
  - {id: olap, title: OLAP}
  - {id: search, title: Search}
  - {id: full-text, title: Full-text Search}
  - {id: vector, title: Vector}
  - {id: ai, title: AI}
  - {id: messaging, title: Messaging}
  - {id: amqp, title: AMQP}
  - {id: cache, title: Cache}
  - {id: key-value, title: Key-Value}
  - {id: in-memory, title: In-Memory}
  - {id: redis-compatible, title: Redis Compatible}
  - {id: object-storage, title: Object Storage}
  - {id: s3, title: S3}
  - {id: backup, title: Backup}
  - {id: cms, title: CMS}
