apiVersion: hivepaas.com/v1
kind: TemplateTags
tags:
  - {id: sql, title: SQL}
  - {id: relational, title: Relational}
  - {id: open-source, title: Open Source}
  - {id: mysql-compatible, title: MySQL Compatible}
  - {id: document, title: Document}
  - {id: json, title: JSON}
  - {id: graph, title: Graph}
  - {id: time-series, title: Time Series}
  - {id: analytics, title: Analytics}
  - {id: olap, title: OLAP}
  - {id: search, title: Search}
  - {id: full-text, title: Full-text Search}
  - {id: vector, title: Vector}
  - {id: ai, title: AI}
  - {id: messaging, title: Messaging}
  - {id: amqp, title: AMQP}
  - {id: cache, title: Cache}
  - {id: key-value, title: Key-Value}
  - {id: in-memory, title: In-Memory}
  - {id: redis-compatible, title: Redis Compatible}
  - {id: object-storage, title: Object Storage}
  - {id: s3, title: S3}
  - {id: backup, title: Backup}
  - {id: cms, title: CMS}
  - {id: automation, title: Automation}
  - {id: git, title: Git}
  - {id: wiki, title: Wiki}
  - {id: llm, title: LLM}
  - {id: identity, title: Identity}
  - {id: sso, title: Single Sign-On}
  - {id: passwords, title: Password Manager}
  - {id: monitoring, title: Monitoring}
  - {id: metrics, title: Metrics}
  - {id: dashboards, title: Dashboards}
  - {id: uptime, title: Uptime}
  - {id: web-analytics, title: Web Analytics}
  - {id: privacy, title: Privacy}
  - {id: tasks, title: Tasks}
  - {id: project-management, title: Project Management}
  - {id: low-code, title: Low-Code}
  - {id: spreadsheet, title: Spreadsheet}
  - {id: email, title: Email}
  - {id: testing, title: Testing}
  - {id: notifications, title: Notifications}
  - {id: chat, title: Chat}
  - {id: business-intelligence, title: Business Intelligence}
  - {id: documents, title: Documents}
  - {id: collaboration, title: Collaboration}
  - {id: team-chat, title: Team Chat}
  - {id: files, title: File Sync}
  - {id: vpn, title: VPN}
  - {id: networking, title: Networking}
  - {id: dns, title: DNS}
  - {id: mqtt, title: MQTT}
  - {id: iot, title: IoT}
  - {id: voice, title: Voice Chat}
  - {id: file-transfer, title: File Transfer}
  - {id: cloudflare, title: Cloudflare}
  - {id: containers, title: Containers}
  - {id: error-tracking, title: Error Tracking}
  - {id: geospatial, title: Geospatial}
  - {id: secrets, title: Secrets Management}
  - {id: feature-flags, title: Feature Flags}
  - {id: notes, title: Notes}
  - {id: whiteboard, title: Whiteboard}
  - {id: ecommerce, title: E-commerce}
  - {id: forum, title: Forum}
  - {id: blog, title: Blog}
  - {id: scheduling, title: Scheduling}
  - {id: game-server, title: Game Server}
